支持分类加载
linuxdeepin/deepin-tweak pull request #10
Opened 2022-10-19 05:07 UTC by justforlxz

可以讨论一下具体要支持哪些分类，目前只是假设了几个，只有 `其他` 分类是固定加载外部插件，其他分类均是内置模块。

其他模块暂无实现。

https://user-images.githubusercontent.com/12298476/196602202-3098965b-bfc8-4935-a63c-7c3bca6c89ab.mp4

2022-10-19 05:08 UTC, justforlxz commented
需要等待 https://github.com/linuxdeepin/deepin-tweak/pull/9 review.

2022-10-19 09:40 UTC, BLumia commented
https://github.com/linuxdeepin/deepin-tweak/actions/runs/3278944400/attempts/1#summary-8975451680

图标的许可声明漏掉了

2022-10-22 02:08 UTC, linuxlionking commented
UI是用了 行云设计  吧

2022-10-22 03:34 UTC, justforlxz commented
> UI是用了 行云设计 吧

是的，这个项目使用了即将在 v23 上使用的 qml 控件。不过界面的整体设计是 deepin design sig 的成员提供的，部分控件是 dtk 提供的直接样式。

2022-10-24 02:17 UTC, zccrs requested changes

2022-10-24 02:17 UTC, zccrs commented on plugins/org.deepin.tweak.titlebar/main.qml
> +        Layout.topMargin: 10
这些UI上的常量值在整个程序中都不会有太多类，放一个地方统一定义些属性用，不要到处直接写。

2022-10-24 02:17 UTC, zccrs commented on src/maincomponentplugin/pluginlistmodel.h
> +    QMutex *mutex;
有初始化吗

2022-10-24 02:17 UTC, zccrs commented on src/maincomponentplugin/qml/Categories/Application.qml
> +        text: 'Application Page'
不翻译吗

2022-10-24 02:17 UTC, zccrs commented on src/maincomponentplugin/qml/Categories/Application.qml
> +}
尾部空一行，其它文件也是

2022-10-24 02:17 UTC, zccrs commented on src/maincomponentplugin/qml/Categories/Other.qml
> +        Layout.minimumHeight: 5 * 36
为什么是这个值？

2022-10-24 02:17 UTC, zccrs commented on src/maincomponentplugin/qml/Categories/Other.qml
> +                        item.color = Qt.rgba(1, 1, 1, 0.4)
不要直接这样写颜色，颜色要同时适配light和 dark模式

2022-10-24 02:17 UTC, zccrs commented on src/maincomponentplugin/qml/Category.qml
> +        color: '#ffffff'
同上

2022-10-24 02:17 UTC, zccrs commented on src/maincomponentplugin/qml/CategoryModel.qml
> +import QtQuick 2.0
后面空一行，保持格式统一

2022-11-03 06:42 UTC, justforlxz commented on src/maincomponentplugin/qml/Categories/Other.qml
> +        Layout.minimumHeight: 5 * 36
为了居中显示，先约束了五个数量。

2022-11-03 06:50 UTC, justforlxz commented
<img width="633" alt="image" src="https://user-images.githubusercontent.com/12298476/199661871-6cd8d174-0443-4359-8c96-dc50b842b937.png">

<img width="630" alt="image" src="https://user-images.githubusercontent.com/12298476/199661895-cf05c1af-93e9-4584-95e6-fe710852224b.png">

2022-11-03 07:26 UTC, zccrs requested changes

2022-11-03 07:26 UTC, zccrs commented on src/maincomponentplugin/qml/Utils/utils.qml
> +    property int margin: 10
定义了没看到在代码使用呀，代码里还是直接写的changliang

2022-11-03 07:26 UTC, zccrs commented on src/maincomponentplugin/qml/Utils/utils.qml
> +    property string transparent: 'transparent'
一般没这样定义的，这里属性名应该是个有意义的值，就像 margin 属性，它的值为 10, 但是如果定义一个 
property int ten: 10 这样的属性就没有意义了。

2022-11-03 07:26 UTC, zccrs commented on src/preloadplugin/Preload.qml
> +        //        enableInWindowBlendBlur: true
这是格式化错了吧

2022-11-07 06:32 UTC, zccrs approved these changes

2022-11-07 06:37 UTC, merged