feat: add a new plugin
linuxdeepin/deepin-tweak pull request #16
Opened 2022-12-09 07:46 UTC by justforlxz

支持简单的方式编辑环境变量。

没有做任何安全检查，用户需要自己对输入的文本进行安全保障。

如果因为错误的内容导致无法进入桌面，可在 tty 登录后删除 $HOME/.dde_env 文件恢复环境变量。

2022-12-09 07:47 UTC, justforlxz commented
![截图_deepin-tweak_20221209154324](https://user-images.githubusercontent.com/12298476/206651526-35198b76-515d-4c97-a25c-4a290cb6d139.png)

2022-12-16 08:04 UTC, zccrs requested changes

2022-12-16 08:04 UTC, zccrs commented on plugins/org.deepin.tweak.environment/main.qml
> +      }
这个对齐很奇怪呀

2022-12-16 08:07 UTC, zccrs requested changes

2022-12-16 08:07 UTC, zccrs commented on plugins/org.deepin.tweak.environment/main.qml
> +        text: qsTr('Please modify environment variables carefully.\nYou must clearly understand the importance of system environment variables. This operation is irreversible.\nIf there is a problem,
也应该加个说明注销重新登录才会生效

2022-12-16 08:07 UTC, zccrs commented on plugins/org.deepin.tweak.environment/main.qml
> +        wrapMode: Text.WrapAnywhere
用 Text.WordWrap 更合理，不然把单词也给拦腰截断了

2022-12-16 08:07 UTC, zccrs commented on plugins/org.deepin.tweak.environment/main.qml
> +        text: qsTr('Please modify environment variables carefully.\nYou must clearly understand the importance of system environment variables. This operation is irreversible.\nIf there is a problem,
另外这里边怎么加了这么多的'\n'，不是自动换行的吗

2022-12-26 02:07 UTC, zccrs requested changes

2022-12-26 02:07 UTC, zccrs commented on plugins/org.deepin.tweak.environment/main.qml
> +      }
还是不对

2022-12-26 02:29 UTC, zccrs approved these changes

2022-12-26 08:51 UTC, merged