fix: update plugin info
linuxdeepin/deepin-tweak pull request #23
Opened 2023-01-05 02:50 UTC by justforlxz

add plugin.json

Log:

2023-01-09 01:57 UTC, zccrs approved these changes

2023-01-09 01:58 UTC, zccrs requested changes

2023-01-09 01:58 UTC, zccrs commented on .reuse/dep5
> +Files: *.qrc src/maincomponentplugin/qml/Utils/qmldir *.json
*.json 是不是太宽泛了？

2023-01-09 01:58 UTC, zccrs commented
commit log 好好写一下

2023-04-21 01:32 UTC, justforlxz commented
https://github.com/linuxdeepin/deepin-tweak/pull/30 有人提交了，这个 pr 关闭。

2023-04-21 01:32 UTC, closed without merging