feat: add titlebar plugin
linuxdeepin/deepin-tweak pull request #6
Opened 2022-09-13 08:34 UTC by justforlxz

init titlebar plugin

Log: 添加内置模块 标题栏定制

2022-09-21 07:37 UTC, BLumia approved these changes

2022-09-22 02:14 UTC, zccrs requested changes

2022-09-22 02:14 UTC, zccrs commented on src/plugins/org.deepin.tweak.titlebar/main.qml
> +    id: frame
id 一般都是写在最前面

2022-09-22 02:14 UTC, zccrs commented on src/plugins/org.deepin.tweak.titlebar/main.qml
> +                               const path = getEnv('HOME') + '/.local/share/deepin/themes/deepin/'+ theme + '/titlebar.ini';
不应该直接从环境变量读，用 DStandrdPath

2022-09-22 02:14 UTC, zccrs commented on src/plugins/org.deepin.tweak.titlebar/main.qml
> +                               const value = getEnv('HOME') + '/.local/share/deepin/themes/deepin/light/titlebar.ini';
同上

2022-09-22 02:14 UTC, zccrs commented on src/plugins/org.deepin.tweak.titlebar/main.qml
> +            text: qsTr("Accept")
是不是用 Apply 更合适

2022-09-28 05:31 UTC, zccrs requested changes

2022-09-28 05:31 UTC, zccrs commented on src/plugins/org.deepin.tweak.titlebar/main.qml
> +            onClicked: () => {
不需要用 () =>，直接写 onClicked: {} 就可以

2022-09-28 05:31 UTC, zccrs commented on src/plugins/org.deepin.tweak.titlebar/main.qml
> +    Component.onCompleted: () => {
同上

2022-09-28 06:21 UTC, zccrs approved these changes

2022-09-28 06:51 UTC, merged